services:
  postgres:
    image: postgres:16
    container_name: cfmigrations_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cfmigrations_testing
      POSTGRES_USER: cfmigrations_testing
      POSTGRES_PASSWORD: cfmigrations_testing
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
