name: Cron

on:
  schedule:
    - cron:  0 0 * * 1

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        cfengine: ["lucee@5", "lucee@6", "adobe@2021", "adobe@2023", "adobe@2025", "boxlang@1", "boxlang-cfml@1"]
        experimental: [false]
        coldbox: ["coldbox@6", "coldbox@7", "coldbox@be"]
        include:
          - cfengine: "lucee@be"
            experimental: true
          - cfengine: "adobe@be"
            experimental: true
          - cfengine: "boxlang@be"
            experimental: true
          - cfengine: "boxlang-cfml@be"
            experimental: true
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: cfmigrations_testing
          POSTGRES_PASSWORD: cfmigrations_testing
          POSTGRES_DB: cfmigrations_testing
        ports:
          - 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup CommandBox CLI
        uses: Ortus-Solutions/setup-commandbox@v2.0.1
        with:
          installSystemModules: true
          install: commandbox-boxlang

      - name: Initial Server Start (so lex extensions are picked up)
        env:
          DB_HOST: localhost
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          DB_NAME: cfmigrations_testing
          DB_USER: cfmigrations_testing
          DB_PASSWORD: cfmigrations_testing
        run: |
          box config set modules.commandbox-dotenv.checkEnvPreServerStart=false
          box server start serverConfigFile="server-${{ matrix.cfengine }}.json" --noSaveSettings --debug
          sleep 30

      - name: Install dependencies
        run: |
          box install --verbose
          box install ${{ matrix.coldbox }} --noSave

      - name: Restart server (so extensions are picked up)
        env:
          DB_HOST: localhost
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          DB_NAME: cfmigrations_testing
          DB_USER: cfmigrations_testing
          DB_PASSWORD: cfmigrations_testing
        run: |
          box server restart serverConfigFile="server-${{ matrix.cfengine }}.json" --debug
          sleep 30

      - name: Run TestBox Tests
        env:
          DB_HOST: localhost
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          DB_NAME: cfmigrations_testing
          DB_USER: cfmigrations_testing
          DB_PASSWORD: cfmigrations_testing
        continue-on-error: ${{ matrix.experimental }}
        run: box testbox run