name: PRs and Branches

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
  pull_request:
    branches:
      - main
      - master
      - development

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        cfengine: ["lucee@5", "adobe@2018"]
        coldbox: ["coldbox@6"]
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: cfmigrations_testing
          POSTGRES_PASSWORD: cfmigrations_testing
          POSTGRES_DB: cfmigrations_testing
        ports:
          - 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11 

      - name: Set Up CommandBox
        uses: elpete/setup-commandbox@v1.0.0

      - name: Initial Server Start (so lex extensions are picked up)
        env:
          DB_HOST: localhost
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          DB_NAME: cfmigrations_testing
          DB_USER: cfmigrations_testing
          DB_PASSWORD: cfmigrations_testing
        run: |
          box config set modules.commandbox-dotenv.checkEnvPreServerStart=false
          box server start cfengine=${{ matrix.cfengine }}
          sleep 30
      
      - name: Install dependencies
        run: |
          box install --verbose
          box install ${{ matrix.coldbox }} --noSave
      
      - name: Restart server (so extensions are picked up)
        env:
          DB_HOST: localhost
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          DB_NAME: cfmigrations_testing
          DB_USER: cfmigrations_testing
          DB_PASSWORD: cfmigrations_testing
        run: |
          box server restart
          sleep 30

      - name: Run TestBox Tests
        env:
          DB_HOST: localhost
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          DB_NAME: cfmigrations_testing
          DB_USER: cfmigrations_testing
          DB_PASSWORD: cfmigrations_testing
        run: box testbox run

  format:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11 

      - name: Set Up CommandBox
        uses: elpete/setup-commandbox@v1.0.0
      
      - name: Install CFFormat
        run: box install commandbox-cfformat
      
      - name: Run CFFormat
        run: box run-script format

      - name: Commit Format Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply cfformat changes